MOONLINE_LEFT_LINE=1

MOONLINE_LEFT1_1=(user)
MOONLINE_LEFT1_2=(current_directory)
MOONLINE_LEFT1_3=()
MOONLINE_LEFT1_4=()

MOONLINE_RIGHT1=(date)
MOONLINE_RIGHT2=()
MOONLINE_RIGHT3=()
MOONLINE_RIGHT4=()

MOONLINE_PROMPT=""
